image: gradle:jdk11

variables:
  CI: "true"
  GIT_STRATEGY: clone
  GIT_FETCH_EXTRA_FLAGS: --tags
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:  # List of stages for jobs, and their order of execution
  - build
  - test
  - publish

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

# everytime we merge a branch into the main
release:
  environment: production
  stage: publish
  script:
    - gradle release
    - gradle publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
